### ISSUE TITLE
Get Coq installed and running

### ISSUE THREAD

**Issue by ChannyClaus** [mfount/chicken#8]
I heard it's bitch to get Coq installed and running. Probz should get it done by the same date the last pset's due?

**Comment by mfount** [comment]
Is everyone ok with using `coq-8.4pl5`? We should probably standardize on a version.

**Comment by ChannyClaus** [comment]
Sure — I probably won’t have time to install it until next week but I’m fine with using it.

**Comment by mfount** [comment]
ok, cool. I'm trying to install with homebrew on OS X now, but it's not quite working.

Also, let's standardize on an IDE, if that's ok with everyone. I think Emacs + Proof General is the most well-supported method. (Though I'm going to use evil-mode to emulate vim in emacs because emacs, ugh, gross.)

**Comment by ChannyClaus** [comment]
Can I stick with Sublime 2……?

**Comment by mfount** [comment]
right, I know, it's frustrating. You're welcome to give it a shot, obviously, but everything that I've read on the matter of using coq is pretty adamant about using Proof General, for some reason that we might figure out.

Maybe let's not worry about IDEs until we can tell if it's necessary or not.

**Comment by bwetherfield** [comment]
It looks like they also brought out coq-8.4p6 today!

**Comment by bwetherfield** [comment]
*coq-8.4pl6
